version: "3.7"

services:

  backend:
    build: .
    command: |
      bash -c 'gunicorn src.indibook.adapters.entrypoints.application:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001'
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8001:8001"
networks:
  default:
    external:
      name: indibook_docker_net